# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/udon/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter udon CPH2487 aston,$(TARGET_DEVICE)),)

endif
